### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by saketguru** [halolimat/LNEx#2]
I am not able to execute the code for the sample text in the README.
PFA the screenshot:

<img width="1334" alt="screen shot 2017-10-06 at 6 39 26 pm" src="https://user-images.githubusercontent.com/32143784/31301126-c3f7fad6-aac5-11e7-966d-d882b89844e5.png">

**Comment by ReemSuwaileh** [comment]
I get the same error when I try preprocessing the tweet:
`tweet = "RT @nixyyyyyy: Saidapet is scary. The Bridge is flooding & it's bringing cylinders, fridges etc #ChennaiFloods #Chennairains https://t.co/q"
ptweet = preprocess_tweet(tweet)
print(ptweet)`

I get the following error:
`ValueError                                Traceback (most recent call last)
<ipython-input-6-bcc41469b991> in <module>()
      1 tweet = "#ChennaiFloods #Chennairains"
----> 2 ptweet = preprocess_tweet(tweet)
      3 print(ptweet)

<ipython-input-5-8a85d7742644> in preprocess_tweet(tweet)
     52         # breaks the hashtag
     53         #print(list(segment(text)))
---> 54         segments = segment(_h)
     55         print(segments)
     56         # concatenate the tokens with spaces between them

C:\ProgramData\Anaconda3\lib\site-packages\wordsegment\__init__.py in segment(self, text)
    157     def segment(self, text):
    158         "Return list of words that is the best segmenation of `text`."
--> 159         return list(self.isegment(text))
    160 
    161 

C:\ProgramData\Anaconda3\lib\site-packages\wordsegment\__init__.py in isegment(self, text)
    143         for offset in range(0, len(clean_text), size):
    144             chunk = clean_text[offset:(offset + size)]
--> 145             _, chunk_words = search(prefix + chunk)
    146             prefix = ''.join(chunk_words[-5:])
    147             del chunk_words[-5:]

C:\ProgramData\Anaconda3\lib\site-packages\wordsegment\__init__.py in search(text, previous)
    130                     yield (prefix_score + suffix_score, [prefix] + suffix_words)
    131 
--> 132             return max(candidates())
    133 
    134         # Avoid recursion limit issues by dividing text into chunks, segmenting

ValueError: max() arg is an empty sequence
`

I tried downgrading wordsegement to 1.3.0 and 1.2.0, but still get the error above.

Could you suggest something I can try to successfully use the preprocessing code, please?

**Comment by halolimat** [comment]
Salam Reem,

Are you using Python 2 or 3?

-Hussein

**Comment by ReemSuwaileh** [comment]
Salam Hussein,

I'm using python 3

Reem

**Comment by halolimat** [comment]
OK, I am using wordsegment 1.3.1 and it works without any issues for me.
You can install it as so:
```
pip install wordsegment==1.3.1
```

This is my code: 
```python

import sys
sys.path.append("LNEx")
import LNEx as lnex

tweet = "RT @nixyyyyyy: Saidapet is scary. The Bridge is flooding & it's bringing cylinders, fridges etc #ChennaiFloods #Chennairains https://t.co/q".lower()
ptweet = lnex.core.preprocess_tweet(tweet)
print(ptweet)

```

Please pull the latest code because it seems the code was not removing URLs by mistake.

Let me know if this fixes your problem!

Thanks,
Hussein

**Comment by ReemSuwaileh** [comment]
Thanks a lot!
It works when I use your code above, but it doesn't work when I use it in isolation from LNEx (my old way).

**Comment by halolimat** [comment]
I will close this issue then.

Thanks, 
Hussein

**Comment by faisaljawad** [comment]
Add "load()" when you write "from wordsegment import load, segment"
This worked for me. 

![image](https://user-images.githubusercontent.com/40547804/76698065-3ceadb80-66c0-11ea-9f52-7d73faf3490b.png)
