### ISSUE TITLE
Dependencies 

### ISSUE THREAD

**Issue by senjed** [halolimat/LNEx#9]
It took me some time to resolve the dependencies. So, I would like to share my experience. 
To use an older version of ElasticSearch this version of the data "photon-ES-17-db-171019.tar.bz2" should be used with version 0.2.7 of the photon (Oct 2016). 
I got the "index missing error" when using the latest version of data (the one that README suggests.) 
Also, please add the required version of elastic search to the requirements.txt. Normally, it downloads the latest version but the required version is 2.0.0 >elasticsearch>= 1.0.0. Thus, setup.py cannot terminate successfully.

Many thanks, 
Moniba

**Comment by halolimat** [comment]
Hello Moniba,

Thanks for sharing. We already have this info in the requirements file as:
"elasticsearch-dsl<2.0.0" over here https://github.com/halolimat/LNEx/blob/master/requirements.txt

**Comment by halolimat** [comment]
Can you please test it for me, I noticed now that you are talking about Elasticsearch not Elasticsearch-DS.

Thanks,
Hussein

**Comment by senjed** [comment]
It installs the elasticsearch version 6. So, I added the "elasticsearch==1.9.0" to requirements.txt to fix this.

**Comment by halolimat** [comment]
I am not sure I can replicate this error you are reporting. Installing the correct version of Elasticsearch-ds do the trick!

I am going to close this issue as it does not affect other users. 

Thanks,
Hussein
